# @name ingress
POST {{host}}/v1/ingress HTTP/1.1
Content-Type: application/json

[
  {
    "timestamp": "2019-05-02T08:13:51.773",
    "deviceId": "test11",
    "x": 1.0,
    "y": 2.0,
    "z": 3.0
  },
  {
    "timestamp": "2019-05-02T08:13:51.773",
    "deviceId": "test",
    "x": 1.0,
    "y": 2.0,
    "z": 3.0
  },
  {
    "timestamp": "2019-05-02T08:13:51.773",
    "deviceId": "test",
    "x": 1.0,
    "y": 2.0,
    "z": 3.0
  },
  {
    "timestamp": "2019-05-02T08:13:51.773",
    "deviceId": "test",
    "x": 1.0,
    "y": 2.0,
    "z": 3.0
  },
  {
    "timestamp": "2019-05-02T08:13:51.773",
    "deviceId": "test11",
    "x": 1.0,
    "y": 2.0,
    "z": 3.0
  },
  {
    "timestamp": "2019-05-02T08:13:51.773",
    "deviceId": "test",
    "x": 1.0,
    "y": 2.0,
    "z": 3.0
  },
  {
    "timestamp": "2019-05-02T08:13:51.773",
    "deviceId": "test",
    "x": 1.0,
    "y": 2.0,
    "z": 3.0
  },
  {
    "timestamp": "2019-05-02T08:13:51.773",
    "deviceId": "test",
    "x": 1.0,
    "y": 2.0,
    "z": 3.0
  }
]

###

# @name stats
GET {{host}}/v1/stats/test HTTP/1.1
Cache-Control: no-cache

###

# @name values
GET {{host}}/v1/values/test11 HTTP/1.1
Cache-Control: no-cache